table Metrics
	lineageTag: aef927c1-2551-4f04-9f96-a7702e7aa830

	measure '% Cumplimiento Final' =
			
			VAR TieneAccidente =
			    MAX(vw_supervisor_accidente_critico[tiene_accidente_critico])
			VAR CumplimientoBase =
			    [% Cumplimiento Ponderado]
			RETURN
			IF(
			    TieneAccidente = 1,
			    0,
			    CumplimientoBase
			)
		lineageTag: d2e27007-be27-4ba8-a159-fb62494b1ad7

	measure '% Cumplimiento Manager Base' =
			
			AVERAGEX(
			    VALUES(vw_hr_bonus_base[supervisor_id]),
			    [% Cumplimiento Proporcional]
			)
		lineageTag: 09507c72-ae67-4ebb-9f3a-6ab40ce472cc

	measure '% Cumplimiento Manager Final' =
			
			VAR Base = [% Cumplimiento Manager Base]
			VAR Penalizacion = [Penalizaci贸n Manager]
			RETURN
			Base * (1 - Penalizacion)
		lineageTag: c00960ac-9f9b-4c30-8ff3-24132e6ca54c

	measure '% Cumplimiento Ponderado' =
			
			VAR CumplimientoPonderado =
			    SUMX(
			        vw_hr_bonus_base,
			        vw_hr_bonus_base[pct_cumplimiento] * vw_hr_bonus_base[peso]
			    )
			VAR PesoTotal =
			    SUM(vw_hr_bonus_base[peso])
			RETURN
			    DIVIDE(CumplimientoPonderado, PesoTotal)
		lineageTag: 45a27056-3a6b-450a-8fb1-a1d064e145c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Cumplimiento Proporcional' =
			
			VAR Factor =
			    MAX(vw_supervisor_proporcionalidad[factor_proporcional])
			VAR CumplimientoFinal =
			    [% Cumplimiento Final]   -- ya incluye bloqueo por accidente
			RETURN
			CumplimientoFinal * Factor
		lineageTag: 134d43fa-9d07-4e33-9e90-68069afebc9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clasificaci贸n Final' =
			
			VAR pct = [% Cumplimiento Final]
			RETURN
			SWITCH(
			    TRUE(),
			    pct < 80, "No Cumple",
			    pct >= 80 && pct < 95, "Cumplimiento Parcial",
			    pct >= 95 && pct <= 104, "Cumple",
			    pct > 104, "Supera Cumplimiento",
			    BLANK()
			)
		lineageTag: 7cfec0d8-1d11-424d-be12-8b8e0ed3a78c

	measure 'Clasificaci贸n Manager' =
			
			VAR pct = [% Cumplimiento Manager Final]
			RETURN
			SWITCH(
			    TRUE(),
			    pct < 80, "No Cumple",
			    pct >= 80 && pct < 95, "Cumplimiento Parcial",
			    pct >= 95 && pct <= 104, "Cumple",
			    pct > 104, "Supera Cumplimiento",
			    BLANK()
			)
		lineageTag: 6f6d8721-59cb-4c99-b656-5deba6a674d3

	measure 'Penalizaci贸n Manager' =
			
			VAR TieneAccidenteEquipo =
			    MAX(vw_manager_accidente_critico[equipo_con_accidente_critico])
			RETURN
			IF(
			    TieneAccidenteEquipo = 1,
			    0.25,
			    0
			)
		lineageTag: 8eb78199-ecc2-4fdb-8810-826966b7e1ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Metrics = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

